"""
This is a 'scons' script for compiling the Solstice post-processing programs
that are also here in this directory. https://www.scons.org/. You will also
need the GCC (Linux) / MINGW-w64 (Windows) compilers.
"""

import platform, os

vars = Variables()
vars.Add('INSTALL_PREFIX', "Location where files will be installed", os.path.expanduser("~/Solstice-0.9.0-GNU-Linux64/bin"))

if platform.system()=="Windows":
	env=Environment(tools=['mingw'],ENV=os.environ,variables=vars)
else:
	env = Environment(variables=vars)


progs = 'solpaths','solmaps','solpp','solppraw';
exes = []

env.Append(
	CFLAGS=['-O2']
)

for p in progs:
	exes.append( env.Program(p,['%s.c'%p]) )

for e in exes:
	env.Install("$INSTALL_PREFIX",e)
env.Alias('install',"$INSTALL_PREFIX")

