# This dockerfile can be used to automatically build a full SOLSTICE setup on 
# Ubuntu, in a cleanroom environment. When the build has completed, there will
# be a binary tarball ready for extraction from the image.
#
# To build SOLSTICE using this docker file, 
#
#   docker build --network=host -t solstice-focal -f Dockerfile-focal 
#
# To extract the built file from the docker image, use
#   docker run --rm -it -v $(pwd):/host solstice-focal sh -c "cp solstice-*.tar.gz /host"

FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

# this is a package cache to reduce server load, see https://is.gd/WWOpmA
RUN echo 'Acquire::http { Proxy "http://localhost:3142"; };' > /etc/apt/apt.conf.d/01proxy

RUN apt-get update && apt-get install -y sudo build-essential git wget vim lsb-release 

RUN useradd -s /bin/bash -m john
RUN usermod -aG sudo john
RUN echo "username	ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN apt-get update && apt-get install -y cmake 

WORKDIR /home/john

ENV MAKE_FLAGS="-j7"
ENV BUILD_TYPE="RELEASE"
#ENV BUILD_TYPE="DEBUG"

# RCMAKE
ENV VER_RCMAKE=0.4
RUN sudo su john -c "git clone https://gitlab.com/vaplv/rcmake.git"
WORKDIR /home/john/rcmake

RUN sudo su john -c "git checkout tags/$VER_RCMAKE"
WORKDIR /home/john/rcmake/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# RSYS
ENV VER_RSYS=0.12
WORKDIR /home/john/
RUN sudo su john -c "git clone https://gitlab.com/vaplv/rsys.git"
RUN ls -l
WORKDIR /home/john/rsys
RUN sudo su john -c "git checkout tags/$VER_RSYS"
WORKDIR /home/john/rsys/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# ISPC
ENV VER_ISPC 1.18.1
WORKDIR /home/john/
RUN sudo su john -c "wget https://github.com/ispc/ispc/releases/download/v$VER_ISPC/ispc-v$VER_ISPC-linux.tar.gz"
RUN sudo su john -c "tar zxvf ispc-v$VER_ISPC-linux.tar.gz"
WORKDIR /home/john/ispc-v${VER_ISPC}-linux
RUN sudo su john -c "pwd"
RUN sudo su john -c "ls -l bin"
ENV BIN_ISPC=/home/john/ispc-v${VER_ISPC}-linux/bin/ispc
RUN sudo su john -c "$BIN_ISPC --version"

# EMBREE
RUN apt-get install -y libtbb-dev libglfw3-dev freeglut3-dev libmagick++-dev cmake libopenimageio-dev pkg-config libjpeg-dev libpng-dev
WORKDIR /home/john/
#ENV VER_EMBREE=v2.17.7
#ENV VER_EMBREE=v3.13.1
ENV VER_EMBREE=v3.13.5
RUN sudo su john -c "git clone https://github.com/embree/embree.git"
WORKDIR /home/john/embree
RUN sudo su john -c "git checkout $VER_EMBREE"
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DEMBREE_ISPC_EXECUTABLE=$BIN_ISPC -DCMAKE_INSTALL_PREFIX=/usr/local"
RUN sudo su john -c "make $MAKE_FLAGS"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# STAR-3D
WORKDIR /home/john
ENV VER_STAR3D=tags/0.8.1
RUN sudo su john -c "git clone https://gitlab.com/meso-star/star-3d.git"
WORKDIR /home/john/star-3d
RUN ls
RUN sudo su john -c "git checkout $VER_STAR3D"
WORKDIR /home/john/star-3d/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr/local . && make $MAKE_FLAGS"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# RANDOM123 -- no installation
WORKDIR /home/john
ENV VER_RANDOM123=1.09
RUN sudo su john -c "wget https://www.deshawresearch.com/downloads/download_random123.cgi/Random123-$VER_RANDOM123.tar.gz"
RUN sudo su john -c "tar zxvf Random123-$VER_RANDOM123.tar.gz"
WORKDIR /home/john/Random123-$VER_RANDOM123/examples
RUN sudo su john -c "make"

# STAR-SP
WORKDIR /home/john
ENV VER_STARSP=0.13
RUN sudo su john -c "git clone https://gitlab.com/meso-star/star-sp.git"
WORKDIR /home/john/star-sp
RUN sudo su john -c "git checkout $VER_STARSP"
WORKDIR /home/john/star-sp/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=/home/john/Random123-$VER_RANDOM123 . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# STAR-3DUT
WORKDIR /home/john
ENV VER_STAR3DUT=0.3.2
RUN sudo su john -c "git clone https://gitlab.com/meso-star/star-3dut.git"
WORKDIR /home/john/star-3dut
RUN sudo su john -c "git checkout tags/$VER_STAR3DUT"
WORKDIR /home/john/star-3dut/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# POLYGON
WORKDIR /home/john
ENV VER_POLYGON=0.1.2
RUN sudo su john -c "git clone https://gitlab.com/vaplv/polygon.git"
WORKDIR /home/john/polygon
RUN sudo su john -c "git checkout tags/$VER_POLYGON"
WORKDIR /home/john/polygon/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# STAR-CPR
WORKDIR /home/john
ENV VER_STARCPR=0.1.2
RUN apt-get install -y libpolyclipping-dev
RUN sudo su john -c "git clone https://gitlab.com/meso-star/star-cpr.git"
WORKDIR /home/john/star-cpr
RUN sudo su john -c "git checkout tags/$VER_STARCPR"
WORKDIR /home/john/star-cpr/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# STAR-SF
WORKDIR /home/john
ENV VER_STARSF=0.8
RUN sudo su john -c "git clone https://gitlab.com/meso-star/star-sf.git"
WORKDIR /home/john/star-sf
RUN sudo su john -c "git checkout tags/$VER_STARSF"
WORKDIR /home/john/star-sf/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# SOLSTICE-SOLVER
WORKDIR /home/john
ENV VER_SOLSTICESOLVER=0.9
RUN sudo su john -c "git clone https://gitlab.com/meso-star/solstice-solver.git"
WORKDIR /home/john/solstice-solver
RUN sudo su john -c "git checkout tags/$VER_SOLSTICESOLVER"
WORKDIR /home/john/solstice-solver/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# SOLSTICE-ANIM
WORKDIR /home/john
ENV VER_SOLSTICEANIM=0.2.3
RUN sudo su john -c "git clone https://gitlab.com/meso-star/solstice-anim.git"
WORKDIR /home/john/solstice-anim
RUN sudo su john -c "git checkout tags/$VER_SOLSTICEANIM"
WORKDIR /home/john/solstice-anim/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# STAR-STL
WORKDIR /home/john
ENV VER_STARSTL=0.3.3
RUN sudo su john -c "git clone https://gitlab.com/meso-star/star-stl.git"
WORKDIR /home/john/star-stl
RUN sudo su john -c "git checkout tags/$VER_STARSTL"
WORKDIR /home/john/star-stl/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# SOLSTICE!!!
RUN apt-get install -y libyaml-dev
WORKDIR /home/john
ENV VER_SOLSTICE=0.9.1
RUN sudo su john -c "git clone https://gitlab.com/meso-star/solstice.git"
WORKDIR /home/john/solstice
RUN sudo su john -c "git checkout tags/$VER_SOLSTICE"
WORKDIR /home/john/solstice/cmake
RUN sudo su john -c "cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make $MAKE_FLAGS"
RUN sudo su john -c "make test"
RUN sudo su john -c "make DESTDIR=~/install install"
RUN make install

# CLEAN UP EMBREE BINS

RUN rm -rf /home/john/install/usr/local/bin/embree3

# TAR UP THE BINARY
WORKDIR /home/john
RUN cat /etc/lsb-release
RUN uname -a
#RUN ls install/usr/local/lib
#RUN ldd install/usr/local/bin/solstice
RUN . /etc/lsb-release \
	&& export DIRNAME="solstice-$VER_SOLSTICE-`uname -p`-$DISTRIB_CODENAME" \
	&& echo $DIRNAME \
	&& mv install $DIRNAME \
	&& tar zcvf $DIRNAME.tar.gz $DIRNAME/*

RUN ls -lh *.gz

LABEL description="Solstice $VER_SOLSTICE built on Ubuntu"


